/**
 * Client-side fallback for generateAutomationFromPrompt when server actions are unavailable
 * Returns a lightweight, deterministic plan so the UI can proceed in offline/extension mode.
 */
export async function generateAutomationFromPrompt(input: any) {
  const prompt = (input?.prompt || "").toString();
  const lower = prompt.toLowerCase();
  const steps: any[] = [];
  let neuralLockId: string | undefined;
  let isAmbiguous = false;

  const match = prompt.match(/([A-Z]{2,6}-\d{3,4})/);
  if (match) neuralLockId = match[1];

  if (lower.includes("complete") || lower.includes("homework") || lower.includes("assignment")) {
    steps.push({ description: "Verify current navigation or use base domain", type: "navigate", value: "https://capella.courseroom.com" });
    steps.push({ description: "Verify login state or find 'Dashboard/Courses' link", type: "extract", target: "a[href*='dashboard'], a[href*='course']" });
    steps.push({ description: "Navigate to course list via discovery", type: "click", target: "a[href*='dashboard'], a[href*='course']" });
    steps.push({ description: "Verify course list is loaded", type: "extract", target: ".course-list, .assignment-list" });
    steps.push({ description: "Identify specific pending assignment", type: "extract", target: ".assignment-item:not(.completed)" });
    steps.push({ description: "Open selected assignment details", type: "click", target: ".assignment-item:not(.completed) a" });
    steps.push({ description: "Confirm assignment details are visible", type: "extract", target: ".assignment-instructions, h1" });
    steps.push({ description: "Prepare submission or launch editor", type: "click", target: "button.start-assignment, a.open-editor" });
    steps.push({ description: "Verify editor or submission portal is ready", type: "extract", target: "textarea, .editor-container" });

    if (!neuralLockId) isAmbiguous = true;
  } else if (lower.includes("login")) {
    steps.push({ description: "Navigate to Login Page", type: "navigate" });
    steps.push({ description: "Verify existence of credentials fields", type: "extract", target: "input[type='text'], input[type='password'], input[type='email']" });
    steps.push({ description: "Enter Credentials", type: "type", target: "input[type='text'], input[type='email']", value: "USER_PROVIDED" });
    steps.push({ description: "Submit Login", type: "click", target: "button[type='submit'], .submit-btn" });
    steps.push({ description: "Verify post-login state (Dashboard/Welcome)", type: "extract", target: ".user-dashboard, .welcome-msg, a[href*='logout']" });
  } else if (lower.includes("scan") || lower.includes("survey")) {
    steps.push({ description: "Locate actionable elements on current page", type: "extract", target: "main, [role='main'], #content" });
    steps.push({ description: "Confirm interaction points are identified", type: "extract", target: "button, a, input" });
    steps.push({ description: "Analyze and prioritize tasks by urgency", type: "wait", value: "1000" });
  } else {
    steps.push({ description: "Extract high-value interactions from page", type: "extract", target: "body" });
  }

  return {
    steps,
    reasoning: "Generated by local fallback heuristics (client-side).",
    estimatedRisk: "medium",
    neuralLock: {
      missionId: neuralLockId,
      confidence: neuralLockId ? 0.95 : 0.2,
      reason: neuralLockId ? "Explicit mission code found in prompt" : "No mission code found; ambiguous",
      isAmbiguous,
    },
    classifiedPlatforms: (input?.sharedToolHostnames || []).map((h: string) => ({ hostname: h, type: 'shared_tool', reason: 'Provided hostnames' })),
  };
}
